# name: 定义步骤的名称 给每一个步骤加一个名称，用来标明这个步骤是在做什么事情 
# 一般在Git action中对应的就是：
# Checkout code
# Copy files to server
# SSH to server and restart application
name: Deploy to CentOS Server

# on: 定义触发 Github Actions 运行的事件类型
# 这里触发的是 push，分支 branch 是 main，也就是当我们向 main 分支 push 代码的时候，会出发当前的流水线作业。
on:
  push:
    branches:
      - main

# jobs: 定义一个或多个需要执行的作业。
jobs:
  # deploy: deploy 语句通常用于部署代码或应用到目标环境，例如生产环境或测试环境。 jobs 下边可以有多个 deploy。
  deploy:
    # runs-on: 用于指定在哪个操作系统中运行 job，它允许你在 github actions 中选择一个特定的虚拟机作为 job 的运行环境。它的值可以有这几种形式：
    # 操作系统名称：例如：ubuntu-latest、macos-latest、windows-latest，分别表示最新版本的 Ubuntu、macOS 和 Windows 操作系统。
    # 操作系统版本号：ubuntu-20.04、macos-11.3、windows-2019，分别表示特定版本的 Ubuntu、macOS 和 Windows 操作系统。
    # 自定义虚拟机镜像名称，例如：my-centos-image，表示使用你自己定义的虚拟机镜像。 在每个 job 中可以使用 runs-on 指定不同的操作系统，你可以根据需要选择合适的操作系统环境来执行不同的构建、测试、部署等操作。
    runs-on: ubuntu-latest

    # steps: 定义作业中需要执行的作业。每个步骤都有一个 name 和一个使用的动作。
    steps:
      # name: 也就是任务名称
      # 这里的name就是用来说明，这个是拿来检查代码的
      - name: Checkout code
      # uses: 引用外部的 Action，可以是 github上的 Action 或者是 Docker 镜像。
      # 这里第一步使用了 actions/checkout@v2，它是一个预定义的 github Actions action，用于从指定的仓库中检出代码到当前工作流的工作目录，以便后续步骤可以在该工作目录中执行操作。
      # 第二步使用了 appleboy/scp-action@v0.1.7，它是一个自定义的 github Actions action，用于执行 SCP(Secure Copy Protocol) 命令，用于在不同计算机之间进行文件传输，可以通过配置 host、username、port 等参数来设置 SSH 连接参数；source 是你要复制的资源文件，target 是复制之后输出的位置。这里是把上一步检出的内容(也就是main分支)输出到服务器上的 /home/apps-server/realworld-server/。
      # 第三步使用了 appleboy/ssh-action@v0.1.7，他是一个 github Actions 自定义的一个 Action，用于在 github Actins 工作流中通过 SSH 远程执行命。它可以用于与远程服务器交互，例如部署应用程序、执行远程命令、上传文件等等；也可以通过配置 host、username、port 等参数来设置 SSH 连接的参数，并通过 script 参数来指定要执行的指令。
        uses: actions/checkout@v2

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: './'
          target: /home/apps-server/realworld-server/

          # 这里用的是 appleboy/ssh-action@v0.1.7，它是一个自定义的 github Actions action，用于在 GitHub Actions 工作流中通过 SSH 远程执行命令。它可以与远程服务器交gi互，例如部署应用程序、执行远程命令、上传文件等等；可以通过配置 host、username、port 等参数来设置 SSH 连接的参数，并通过 script 参数来指定要执行的指令。
      - name: SSH to server and restart application
        uses: appleboy/ssh-action@v0.1.7
        with:
            host: ${{ secrets.SERVER_HOST }}.
            username: ${{ secrets.SERVER_USERNAME }}
            password: ${{ secrets.SERVER_PASSWORD }}
            script: |
              cd /home/apps-server/realworld-server
              npm install
              npm run build
              pm2 restart ./dist/src/main.js --name realworld-server
      # 后面还可以添加其他的方式，但是还是必须包含上面的三个步骤
