name: Deploy via SSH

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DigitalOcean Container Registry
        run: |
          echo "${{ secrets.DOCR_TOKEN }}" | docker login --username ${{ secrets.DOCR_USERNAME }} --password-stdin registry.digitalocean.com

      - name: Build Docker image
        run: docker build -t registry.digitalocean.com/jiang-nest/jiang-nest-study:latest .

      - name: Push Docker image
        run: docker push registry.digitalocean.com/jiang-nest/jiang-nest-study:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: SSH to server and deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.DO_SERVER_HOST }}
          username: ${{ secrets.DO_SERVER_USERNAME }}
          key: ${{ secrets.DO_SERVER_SSH_KEY }}
          script_timeout: 300 # 设置超时时间为 300 秒
          retry: 3 # 重试次数
          script: |
            echo "${{ secrets.DOCR_TOKEN }}" | docker login --username ${{ secrets.DOCR_USERNAME }} --password-stdin registry.digitalocean.com
            docker pull registry.digitalocean.com/jiang-nest/jiang-nest-study:latest
            docker ps -q --filter "name=jiang-nest-study" | grep -q . && docker stop jiang-nest-study || echo "Container jiang-nest-study is not running"
            docker ps -a -q --filter "name=jiang-nest-study" | grep -q . && docker rm jiang-nest-study || echo "Container jiang-nest-study does not exist"
            docker run -d --name jiang-nest-study -p 3000:3000 registry.digitalocean.com/jiang-nest/jiang-nest-study:latest

